const SERVICE_DRAINPIPEMONITORINGINFO = 'DrainpipeMonitoringInfo';
const SERVICE_LISTRAINFALLSERVICE = 'ListRainfallService';

module.exports = {
  SERVICE_DRAINPIPEMONITORINGINFO,
  SERVICE_LISTRAINFALLSERVICE,
};
